### PR TITLE
Updated require for electron app.

### PR DESCRIPTION
**Pull request by Vj3k0**
Fixing failure with electron 1.0.0

---

This change is [Reviewable](https://reviewable.io/reviews/mongodb-js/electron-squirrel-startup/3)

### CODE REVIEW

**Comment by Vj3k0** [comment]
Really? Hmm, I got electron error saying that it is not valid electron application. When I did this change, everything worked.
Which version of electron did you use?

**Comment by mitchhentges** [comment]
Confirmed, also not working for me unless this PR is merged. Seems to be related to Electron `1.0.0+` removing deprecated usage, and `app` has to be pulled off of `require('electron')`, now, instead of in it's own `require('app')`.

See the docs [here](https://github.com/electron/electron/blob/master/docs/api/app.md#app)

**Comment by jbleuzen** [comment]
@Vj3k0 I was meaning that your fork was working.
I'm using it until it's merged...

**Comment by develar** [comment]
@imlucas Please apply this PR ASAP, because your module is recommended by electron-builder/windows-installeer and widely used. Please accept PR.

**Comment by mitchhentges** [comment]
Hey all, I've forked this to support `electron@^1.0.0`, and published the fork to npm under the name `electric-squirrel`.

Thanks again to Vj3k0 for the fix!
See the details [here](https://github.com/mitchhentges/electric-squirrel)

**Comment by aaleks** [comment]
+1

**Comment by develar** [comment]
@imlucas If you don't have time, just add me to contributor (+ npm) (I maintainer of electron-builder, so, unlikely I will harm ;)) I really don't want to reinvent the wheel and promote @mitchhentges fork :)

In the future will be cool to move this project to electron-userland org.

**Comment by develar** [comment]
BTW electron-builder has own fork of Squirrel.Windows, so, in the future, https://github.com/electron-userland/electron-builder/issues/409 may be implemented, and such module will be not required (yeah, so easy to create os x app, and so many troubles under windows...).

**Comment by imlucas** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/mongodb-js/electron-squirrel-startup/3)_

**Comment by imlucas** [comment]
published in electron-squirrel-startup@0.2.0

**Comment by develar** [comment]
@imlucas Thanks! Maybe it is time to publish it as `1.0.0`? Because `^0.1.0` will not cover `0.2`. I think there are no planned breaking changes and, so, `1.0.0` can be used.

**Comment by imlucas** [comment]
@develar agreed.  published electron-squirrel-startup@1.0.0

**Comment by imlucas** [comment]
@develar added as a contributor

**Comment by Vj3k0** [comment]
Thanks a lot! Cheers

**Pull request merged**
